namespace SpriteKind {
    export const Finish = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        .......cf...............
        ......cfff..............
        .....cfffff.............
        ....c9bffff.............
        ff.c999bffff............
        fffcb991ffff............
        ffff4b11ffff............
        ffc44f11ffff............
        fcc4ff19ffff............
        fcc4ffb9ffffff..........
        .fcffffffffffcf.........
        ..ffffffffcfcccf........
        ..fffffff4ffffff........
        ..ffffffc44fffff........
        ...cfffcff44ffff........
        ...cfffcfff4cfff........
        ...ccffcfffffff.........
        ..cccffccfffff..........
        .cc44ffccfffff..........
        cc44ffccf.ffff..........
        c44ffffcf..ccf..........
        cffffcfff...............
        ......cff...............
        .......ff...............
        `],
    500,
    false
    )
    controller.moveSprite(mySprite, 100, 100)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Finish, function (sprite, otherSprite) {
    game.gameOver(true)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite, 100, 100)
    animation.runImageAnimation(
    mySprite,
    [img`
        ....ffffff.........ccc..
        ....ffffccf.......cc4f..
        .....ffccccfff...cc44f..
        ....ccf444ffffcccc44ff..
        ...c9b44ffffffffcc4fff..
        ..c999bfffffffffffff3c..
        .cfb99111bfffffffffcffc.
        cfffb11199ffffcccccccfff
        fffffffffffffcfffccfffff
        .fffffffffff44fffff.....
        ..fffffffffcf44fffff....
        ....ffffffffff44ffffc...
        .........ffcfffcffffc...
        .........fccfffffffff...
        ..........fcfffff.......
        ...........fffff........
        `],
    500,
    false
    )
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite, 100, 100)
    animation.runImageAnimation(
    mySprite,
    [img`
        ..ccc.........ffffff....
        ..f4cc.......fccffff....
        ..f44cc...fffccccff.....
        ..ff44ccccffff444fcc....
        ..fff4ccffffffff44b9c...
        ..cffffffffffffffb999c..
        .cffcfffffffffb11199bfc.
        fffcccccccffff99111bfffc
        fffffccfffcfffffffffffff
        .....fffff44fffffffffff.
        ....fffff44fcfffffffff..
        ...cffff44ffffffffff....
        ...cffffcfffcff.........
        ...fffffffffccf.........
        .......fffffcf..........
        ........fffff...........
        `],
    500,
    false
    )
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite, 100, 100)
    animation.runImageAnimation(
    mySprite,
    [img`
        ......ffff.fccff44cc....
        ......fffffccff44cc.....
        ......fffffccffccc......
        .....fffffffcffcc.......
        ....fffc4fffcfffc.......
        ....ffff44ffcfffc.......
        ....fffff44cffffff......
        ....ffffff4fffffff......
        ....fcccfcffffffff......
        .....fcffffffffffcf.....
        ......ffffff9bff4ccf....
        ........ffff91ff4ccf....
        ........ffff11f44c2f....
        ........ffff11b42f2f....
        ........ffff199bcfff....
        ........ffffb999c.ff....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ...............ff.......
        ...............ffc......
        ...............fffcffffc
        ..........fcc..fcffff44c
        ..........ffff.fccff44cc
        ..........fffffccff44cc.
        ..........fffffccffccc..
        .........fffffffcffcc...
        ........fffc4fffcfffc...
        ........ffff44ffcfffc...
        ........fffff44cffffff..
        ........ffffff4fffffff..
        ........fcccfcffffffff..
        .........fcffffffffffcf.
        ..........ffffff9bff4cff
        ............ffff91ff4ccf
        ............ffff11f44ccf
        ............ffff11b4ffff
        ............ffff199bcfff
        ............ffffb999cfff
        .............ffffb9c..ff
        .............fffffc.....
        ..............fffc......
        ...............fc.......
        `],
    500,
    false
    )
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
let Grande: Sprite = null
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ..............ffffff....
    ..fc.........fccffff....
    ..f4c.....fffccccff.....
    ..f44cccccffffffffcc....
    ..ff44cccfffff444fb9c...
    ..cff4ffffffffff44999c..
    .ccffffffffffffff999bfc.
    fcffccffffffffb1111bfffc
    fffcccccccffff9911ffffff
    ffffffcfffcffffffffffff.
    ....ffffff44cfffffffff..
    ...cfffff44fffffffff....
    ...cffff44ffcff.........
    ...cffffcfffccf.........
    ...fffffffffcf..........
    ........ffffc...........
    `, SpriteKind.Player)
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(mySprite)
let mySprite2 = sprites.create(img`
    ..............ffffff....
    ..fc.........fccc2ff....
    ..f4c.....fffccc2ff.....
    ..f44ccccfffff2222cc....
    ..ff44cccfffff4442b9c...
    ..cff4ffffffff2244999c..
    .ccfffffffffff222199b2c.
    fcffccffffffffb1111b222c
    fffcccccccffff991222222f
    ffffffcfffcfff22222222f.
    ....ffffff44cf222222ff..
    ...cfffff44fffffffff....
    ...cffff44ffcff.........
    ...cffffcfffccf.........
    ...fffffffffcf..........
    ........ffffc...........
    `, SpriteKind.Enemy)
mySprite2.setVelocity(10, 1)
mySprite2.follow(mySprite)
tiles.placeOnTile(mySprite, tiles.getTileLocation(8, 12))
tiles.placeOnTile(mySprite2, tiles.getTileLocation(3, 12))
let mySprite3 = sprites.create(img`
    ........................................................
    ........................................................
    ...6............6............6............6.............
    ..676..........676..........676..........676............
    .6776e........6776e........6776.........6776............
    67776effffffe67776effffffe67776........67776............
    e6668ceeeccfff6768eeeeccfff6768eeeeeeeee6668eeeeeeeeb...
    ee668eeeeeeeeee668eceeeeeeee668ecccfffcce668eeeeeeeeeb..
    ee67776eeeeeeee67776eeeeeeee67776eeeeeeee7777eeeeeeeeeb.
    ee6777eeeeeeeee6776eeeeeeeee6776eeeeeeeee6776eeeeeeeeee.
    eee76eeeeeeeeeee76eeeeeeeeeee76eeeeeeeeeee76eeeeeeeeeee.
    eee68eeeeeeeeeee78eeeeeeeeeee78eeeeeeeeeee78eeeeeeeeeee.
    eee68eeeeeeeeeee78eeeeeeeeeee78eeeeeeeeeee78eeeeeeeeeee.
    eee76eeeeeeeeeee76eeeeeeeeeee76eeeeeeeeeee76eeeeeeeeeee.
    ee6777eeeeeeeee6777eeeeeeeee6777eeeeeeeee6777eeeeeeeeee.
    ee66776eeeeeeee66776eeeeeeee66776fccceeee6777eeeeeeeeeb.
    c66eeeeeeeeeee66eeeeeeeeeee66eeeeeeeeeee66eeeeeeeeeeeb..
    f778eeeeeeccff77eeeeeeeeeff77eeeeeeeeeee76ecceeeeeeeb...
    67768........67768........67768........67768............
    .6776.........6776.........6776.........6776............
    ..676..........676..........676..........676............
    ...6............6............6............6.............
    ........................................................
    ........................................................
    `, SpriteKind.Finish)
tiles.placeOnTile(mySprite3, tiles.getTileLocation(13, 12))
let mySprite4 = sprites.create(img`
    . . . . . b b b b b b . . . e . 
    . . . b b f f f f f f f f . . e 
    . . b b f f f f f f f f f f e . 
    . b b f f f f f f f f f f f f . 
    . b f f f f f f f f f f f f f . 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    . b f f f f f f f f f f f f b . 
    . b f f f f f f f f f f f b b . 
    . . b f f f f f f f f f b b . . 
    . . . b b f f f f f f b b . . . 
    . . . . . b b b b b b . . . . . 
    `, SpriteKind.Enemy)
tiles.placeOnTile(mySprite4, tiles.getTileLocation(3, 4))
tiles.placeOnTile(Grande, tiles.getTileLocation(3, 9))
Grande = sprites.create(img`
    . . . . . b b b b b b . . . e . 
    . . . b b f f f f f f f f . . e 
    . . b b f f f f f f f f f f e . 
    . b b f f f f f f f f f f f f . 
    . b f f f f f f f f f f f f f . 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    b f f f f f f f f f f f f f f b 
    . b f f f f f f f f f f f f b . 
    . b f f f f f f f f f f f b b . 
    . . b f f f f f f f f f b b . . 
    . . . b b f f f f f f b b . . . 
    . . . . . b b b b b b . . . . . 
    `, SpriteKind.Player)
